# Generated by Django 6.0.5 on 2026-05-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurificationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(verbose_name='원본 텍스트')),
                ('purified_text', models.TextField(verbose_name='순화된 텍스트')),
                ('mode', models.CharField(choices=[('scholar', '선비 모드'), ('trend', '어쩔티비 모드'), ('cute', '뿌잉뿌잉 모드'), ('rant', '주접 모드'), ('interview', '면접 모드')], default='scholar', max_length=20, verbose_name='순화 모드')),
                ('severity_score', models.IntegerField(default=0, verbose_name='심각도 점수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '순화 기록',
                'ordering': ['-created_at'],
            },
        ),
    ]
