# Generated by Django 6.0.5 on 2026-05-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purificationrecord',
            name='session_key',
            field=models.CharField(default='', max_length=40, verbose_name='세션 키'),
            preserve_default=False,
        ),
    ]
